### ISSUE TITLE
哥们界面做得不错，难得看到界面做得好看的

### ISSUE THREAD

**Issue by OwlAford** [LCJ-MinYa/chat#2]

**Comment by LCJ-MinYa** [comment]
哈哈，谢谢，之前有点设计基础。

**Comment by OwlAford** [comment]
请问后端服务是自己搭建的吗

**Comment by LCJ-MinYa** [comment]
恩，node + mongodb，阿里的centos

**Comment by OwlAford** [comment]
可以讲讲大概的搭建原理吗，我也有点兴趣想学学看，谢谢啦

**Comment by LCJ-MinYa** [comment]
用express来搭建API和路由，mongodb是用的mongoose这个模块，基本上大部分都有用到第三方的模块，其实自己写的基本都是业务逻辑。
